### ISSUE TITLE
Support for gevent 0.13.8

### ISSUE THREAD

**Issue by dmckeone** [saghul/uvent#1]
gevent 0.13.8 (the currently available non-beta version) fails with this traceback:

```
Traceback (most recent call last):
  File "gevent_single.py", line 9, in <module>
    import uvent; uvent.install()
  File "/Library/Python/2.7/site-packages/uvent/__init__.py", line 34, in install
    patch_loop()
  File "/Library/Python/2.7/site-packages/uvent/__init__.py", line 26, in patch_loop
    from gevent.resolver_thread import Resolver
ImportError: No module named resolver_thread
```

Thought I'd file this bug so that it can be recognized as 'not going to be implemented' and 1.0+ only, or as something to be added.

**Comment by saghul** [comment]
uvent relies on the gevent internals from version 1.0, so it will not work with version 0.X. Thanks for reporting it, I'll mention this on the README to avoid confusion. :-)
